
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/goodfood
    username: user
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      encoding: UTF-8

goodfood:
  app:
    jwtSecret: b0bcc54d941472995ae5fad499adccbf640f9bca5f444126c8e37b31893405cfa447be42adf4d5c306209b00f87d48223606c4a2dc487b1f03c68f356c69416e
    jwtExpirationMs: 86400000

springdoc:
  show-actuator: true
