spring:
  datasource:
    url: jdbc:mariadb://goodfood-db:3306/goodfood
    username: user
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      encoding: UTF-8

goodfood:
  app:
    jwtSecret: 99af6388826d2373129098037aca1afc
    jwtExpirationMs: 86400000

springdoc:
  show-actuator: true
