server:
  port: 8080
  error:
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mariadb://goodfood-db:3306/goodfood
    username: user
    password: 123456
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      encoding: UTF-8

springdoc:
  show-actuator: true
