INSERT INTO TBL_CATEGORY (NAME) VALUES ('Cliente');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Nutricionista');

INSERT INTO TBL_USER (NAME, EMAIL, PASSWORD, CATEGORY_ID) VALUES ('Michael', 'michael@email.com', 'senha123', 1);
INSERT INTO TBL_USER (NAME, EMAIL, PASSWORD, CATEGORY_ID) VALUES ('Bruno', 'bruno@email.com', 'senha123', 1);
INSERT INTO TBL_USER (NAME, EMAIL, PASSWORD, CATEGORY_ID) VALUES ('Luan', 'luan@email.com', 'senha123', 1);
INSERT INTO TBL_USER (NAME, EMAIL, PASSWORD, CATEGORY_ID) VALUES ('Felipe', 'felipe@email.com', 'senha123', 2);
INSERT INTO TBL_USER (NAME, EMAIL, PASSWORD, CATEGORY_ID) VALUES ('Gabriel', 'gabriel@email.com', 'senha123', 2);